server:
  port: 80
  context-path: /springbootdemo
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
global:
  projectCode: demp-project-code
  shirosecret: secret-shiro

