server:
  port: 80
  context-path: /springbootdemo
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jndi:
    ignore: true
global:
  projectCode: demp-project-code
  shiroSecret: secret-shiro

